#!/usr/bin/env node
// Extract design tokens from a live reference site using Playwright.
// Usage: node scripts/extract-tokens.mjs [url]

import { chromium } from "playwright";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REFERENCE_URL = process.argv[2] ?? "https://rundlehornsmilesdental.com";
const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const OUT_JSON = resolve(REPO_ROOT, "design/tokens.json");
const OUT_THEME_CSS = resolve(REPO_ROOT, "design/theme.generated.css");
const OUT_SCREENSHOT = resolve(REPO_ROOT, "design/reference-home.png");

const NORMALIZE_COLOR = (c) => {
  if (!c || c === "rgba(0, 0, 0, 0)" || c === "transparent") return null;
  const m = c.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)$/);
  if (!m) return c;
  const [, r, g, b, a] = m;
  const hex =
    "#" +
    [r, g, b]
      .map((n) => Number(n).toString(16).padStart(2, "0"))
      .join("");
  return a !== undefined && Number(a) < 1 ? `${hex} / ${a}` : hex;
};

const run = async () => {
  const browser = await chromium.launch();
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  const page = await ctx.newPage();

  console.log(`→ loading ${REFERENCE_URL}`);
  await page.goto(REFERENCE_URL, { waitUntil: "networkidle", timeout: 60_000 });

  const raw = await page.evaluate(() => {
    const sample = (selector, props) => {
      const el = document.querySelector(selector);
      if (!el) return null;
      const cs = getComputedStyle(el);
      return Object.fromEntries(props.map((p) => [p, cs.getPropertyValue(p)]));
    };

    const colorFrequency = new Map();
    const bump = (key, val) => {
      if (!val) return;
      const k = `${key}::${val}`;
      colorFrequency.set(k, (colorFrequency.get(k) ?? 0) + 1);
    };

    document.querySelectorAll("*").forEach((el) => {
      const cs = getComputedStyle(el);
      bump("color", cs.color);
      bump("background-color", cs.backgroundColor);
      bump("border-color", cs.borderTopColor);
    });

    const colorCounts = [...colorFrequency.entries()].map(([k, n]) => {
      const [prop, value] = k.split("::");
      return { prop, value, count: n };
    });

    const fonts = new Set();
    document.querySelectorAll("h1, h2, h3, p, a, button").forEach((el) => {
      const f = getComputedStyle(el).fontFamily;
      if (f) fonts.add(f);
    });

    return {
      body: sample("body", [
        "font-family",
        "font-size",
        "line-height",
        "color",
        "background-color",
      ]),
      h1: sample("h1", ["font-family", "font-size", "font-weight", "line-height", "color"]),
      h2: sample("h2", ["font-family", "font-size", "font-weight", "line-height", "color"]),
      h3: sample("h3", ["font-family", "font-size", "font-weight", "line-height", "color"]),
      link: sample("a", ["color", "text-decoration-color"]),
      button: sample("button, .button, .btn, [class*='btn']", [
        "background-color",
        "color",
        "border-color",
        "border-radius",
        "padding",
        "font-family",
        "font-weight",
      ]),
      heroCta: sample(
        "a[class*='book'], a[href*='book'], a[href*='appointment'], a[class*='cta']",
        ["background-color", "color", "border-radius", "padding", "font-weight"]
      ),
      fontFamilies: [...fonts],
      colorCounts,
    };
  });

  const norm = (obj) =>
    obj
      ? Object.fromEntries(
          Object.entries(obj).map(([k, v]) => {
            if (k.includes("color")) return [k, NORMALIZE_COLOR(v)];
            return [k, typeof v === "string" ? v.trim() : v];
          })
        )
      : null;

  const topColors = raw.colorCounts
    .map((c) => ({ ...c, value: NORMALIZE_COLOR(c.value) }))
    .filter((c) => c.value && c.value !== "#000000" && c.value !== "#ffffff")
    .sort((a, b) => b.count - a.count)
    .slice(0, 20);

  const tokens = {
    sourceUrl: REFERENCE_URL,
    extractedAt: new Date().toISOString(),
    typography: {
      body: norm(raw.body),
      h1: norm(raw.h1),
      h2: norm(raw.h2),
      h3: norm(raw.h3),
      link: norm(raw.link),
      button: norm(raw.button),
      heroCta: norm(raw.heroCta),
      detectedFamilies: raw.fontFamilies,
    },
    topColorsByFrequency: topColors,
  };

  await mkdir(dirname(OUT_JSON), { recursive: true });
  await writeFile(OUT_JSON, JSON.stringify(tokens, null, 2));
  console.log(`✓ tokens → ${OUT_JSON}`);

  const theme = [
    "/* Auto-generated by scripts/extract-tokens.mjs — DO NOT EDIT BY HAND */",
    `/* Source: ${REFERENCE_URL} */`,
    `/* Extracted: ${tokens.extractedAt} */`,
    "",
    "@theme {",
    `  --color-body: ${tokens.typography.body?.color ?? "#111111"};`,
    `  --color-bg: ${tokens.typography.body?.["background-color"] ?? "#ffffff"};`,
    `  --color-heading: ${tokens.typography.h1?.color ?? "var(--color-body)"};`,
    `  --color-link: ${tokens.typography.link?.color ?? "#0d7c8a"};`,
    tokens.typography.heroCta?.["background-color"]
      ? `  --color-primary: ${tokens.typography.heroCta["background-color"]};`
      : tokens.typography.button?.["background-color"]
      ? `  --color-primary: ${tokens.typography.button["background-color"]};`
      : `  --color-primary: #0d7c8a;`,
    `  --font-sans: ${tokens.typography.body?.["font-family"] ?? "system-ui, sans-serif"};`,
    `  --font-heading: ${tokens.typography.h1?.["font-family"] ?? "var(--font-sans)"};`,
    "}",
    "",
  ].join("\n");

  await writeFile(OUT_THEME_CSS, theme);
  console.log(`✓ @theme block → ${OUT_THEME_CSS}`);

  await page.screenshot({ path: OUT_SCREENSHOT, fullPage: true });
  console.log(`✓ reference screenshot → ${OUT_SCREENSHOT}`);

  await browser.close();
};

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
